Repository Callbritton/futbol, pull requests merged in 2020-07, with the labels that each got.

#1 Stat tracker
  .gitignore
  Gemfile
  lib/stat_tracker.rb
  runner.rb
  test/stat_tracker_test.rb
  test/test_helper.rb
Labels: Author needs review, Reviewer merges to development

#2 Stat tracker test
  data/dummy_file_game_teams.csv
  data/dummy_file_games.csv
  data/dummy_file_teams.csv
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Reviewer merges to Development, Screen Share Peer Tested

#3 Create hash
  lib/create_hash.rb
  lib/game_statistics.rb
  test/create_hash_test.rb
  test/game_statistics_test.rb
Labels: Reviewer merges to Development, Screen Share Peer Tested

#4 Game statistics highest total score
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Author needs review, Author thinks ready to merge, Reviewer merges to Game_Statistics_Highest_Total_S

#5 Update create_hash renamed to game
  lib/create_hash.rb
  lib/game.rb
  test/game_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Game_Statistics

#6 Game statistics lowest total score
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Reviewer merges to Game_Statistics

#7 Game statistics count of games by season
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Reviewer merges to Game_Statistics

#8 Game statistics average goals per game
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Reviewer merges to Game_Statistics

#9 Game statistics avg goals by season
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Author resolved conversations, Reviewer merges to Game_Statistics

#10 Game statistics percentage home wins
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Game_Statistics

#11 Game statistics percentage visitor wins
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Game_Statistics, Screen Share Peer Tested

#12 Game statistics percentage ties
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Author resolved conversations, Reviewer merges to Game_Statistics, Screen Share Peer Tested

#13 Game statistics
  lib/create_hash.rb
  lib/game.rb
  lib/game_statistics.rb
  test/game_statistics_test.rb
  test/game_test.rb
Labels: Author resolved conversations, Reviewer merges to Development

#14 League statistics count of teams
  lib/game_statistics.rb
  lib/league_statistics.rb
  test/league_statistics_test.rb
Labels: Author thinks ready to merge, Reviewer merges to League_Statistics

#15 Created file to read games csv file
  lib/game_data.rb
  test/game_data_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#16 Created file to read team csv file
  data/dummy_file_teams.csv
  lib/team_data.rb
  test/team_data_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#17 Csv game team data - Create file to read game team csv file
  lib/game_team_data.rb
  test/game_team_data_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#18 Create file to read game&team joint csv file
  lib/data_object_creatable.rb
  test/data_object_creatable_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#19 Update to refactor GameData class and test
  lib/game_data.rb
  lib/stat_tracker.rb
  test/game_data_test.rb
Labels: Author resolved conversations, Author thinks ready to merge, Screen Share Peer Tested

#20 Game statistics redo
  Gemfile.lock
  lib/game_data.rb
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#21 Team and game team data
  lib/game.rb
  lib/game_statistics.rb
  lib/game_team_data.rb
  lib/team_data.rb
  test/game_data_test.rb
  test/game_team_data_test.rb
  test/game_test.rb
  test/team_data_test.rb
Labels: Reviewer merges to Development, Screen Share Peer Tested

#22 League statistics redo
  lib/league_statistics.rb
  test/league_statistics_test.rb
Labels: Reviewer merges to Development, Screen Share Peer Tested

#23 Season statistics group sunday
  lib/season_statistics.rb
  test/season_statistics_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#24 Team statistics PR
  lib/team_statistics.rb
  test/team_statistics_test.rb
Labels: Author resolved conversations, Author thinks ready to merge, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#25 Update spec harness before team
  lib/game_data.rb
  lib/game_statistics.rb
  lib/game_team_data.rb
  lib/league_statistics.rb
  lib/season_statistics.rb
  lib/stat_tracker.rb
  lib/team_data.rb
  test/game_data_test.rb
  test/game_statistics_test.rb
  test/game_team_data_test.rb
  test/league_statistics_test.rb
  test/season_statistics_test.rb
  test/team_data_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#26 Implement futbol data super class
  .gitignore
  .keep
  README.md
  lib/.keep
  lib/data_object_creatable.rb
  lib/futbol_data.rb
  lib/game_data.rb
  lib/game_statistics.rb
  lib/game_team_data.rb
  lib/league_statistics.rb
  lib/season_statistics.rb
  lib/stat_tracker.rb
  lib/team_data.rb
  lib/team_statistics.rb
  test/.keep
  test/data_object_creatable_test.rb
  test/futbol_data_test.rb
  test/game_data_test.rb
  test/game_statistics_test.rb
  test/game_team_data_test.rb
  test/league_statistics_test.rb
  test/season_statistics_test.rb
  test/team_data_test.rb
  test/team_statistics_test.rb
Labels: Author resolved conversations, Reviewer merges to Development, Reviewer second review complete, Screen Share Peer Tested

#27 Create module for object instantiation
  lib/futbol_creatable.rb
  lib/game_statistics.rb
  lib/helpable.rb
  lib/league_statistics.rb
  lib/season_statistics.rb
  lib/team_statistics.rb
  test/season_statistics_test.rb
Labels: Author needs review, Author thinks ready to merge, Reviewer adds line comments, Reviewer merges to Development

#28 Stat tracker spec test
  data/dummy_file_game_teams.csv
  data/dummy_file_games.csv
  lib/game_statistics.rb
  lib/season_statistics.rb
  lib/stat_tracker.rb
  test/game_statistics_test.rb
  test/league_statistics_test.rb
  test/season_statistics_test.rb
Labels: Author resolved conversations, Author thinks ready to merge, Reviewer adds line comments, Reviewer merges to Development, Screen Share Peer Tested

#29 Refactoring and polish
  README.md
  lib/futbol_data.rb
  lib/helpable.rb
  lib/league_statistics.rb
  lib/season_statistics.rb
  lib/stat_tracker.rb
  lib/team_statistics.rb
  test/futbol_data_test.rb
  test/game_statistics_test.rb
  test/league_statistics_test.rb
  test/season_statistics_test.rb
  test/stat_tracker_test.rb
  test/team_statistics_test.rb
  test/test_helper.rb
Labels: Author resolved conversations, Author thinks ready to merge, Reviewer adds line comments, Screen Share Peer Tested

#32 Game statistics polish
  lib/game_statistics.rb
  test/game_statistics_test.rb
Labels: Author resolved conversations, Author thinks ready to merge, Reviewer merges to Development

#31 Add polish and comments when untestable
  lib/team_statistics.rb
  test/team_statistics_test.rb
Labels: Author resolved conversations, Author thinks ready to merge, Reviewer adds line comments, Reviewer merges to Development

#30 Update to get rid of white space
  test/season_statistics_test.rb
Labels: Author resolved conversations, Author thinks ready to merge, Reviewer adds line comments, Reviewer merges to Development

#33 League statistics polish
  lib/futbol_data.rb
  lib/helpable.rb
  lib/league_statistics.rb
  lib/stat_tracker.rb
  test/league_statistics_test.rb
Labels: Author resolved conversations, Reviewer adds line comments, Reviewer merges to Development

#34 Pull Request from development to main
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  lib/.keep
  lib/futbol_creatable.rb
  lib/futbol_data.rb
  lib/game_statistics.rb
  lib/helpable.rb
  lib/league_statistics.rb
  lib/season_statistics.rb
  lib/stat_tracker.rb
  lib/team_statistics.rb
  test/.keep
  test/futbol_data_test.rb
  test/game_statistics_test.rb
  test/league_statistics_test.rb
  test/season_statistics_test.rb
  test/team_statistics_test.rb
  test/test_helper.rb
Labels: Author resolved conversations, Author thinks ready to merge, Reviewer adds line comments, Screen Share Peer Tested
